spring:
  profiles:
    active: default

security:
  require-ssl: true

server:
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}
        key-alias: ${keystoreSSLKey:tomcat}
        key-store-type: PKCS12
