spring:
  profiles:
    active: default

server:
    ssl:
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}
        key-alias: ${keystoreSSLKey:tomcat}
        key-store-type: PKCS12
